Replace empty short_message with default string
Graylog throws the following exception when `short_message`
is the empty string:
```
java.lang.IllegalArgumentException: GELF message <[UUID]> (received from <[IP addr:port]>) has empty mandatory "short_message" field.
```

Instead of supplying an empty string in the absence of a `message`
field, format the level and the word "Event" (e.g. `ERROR Event`).